import path from "node:path";

// Copied from OpenCode's TUI language mapping and normalized for OpenTUI diffs.
export const LANGUAGE_EXTENSIONS: Record<string, string> = {
  ".abap": "abap",
  ".astro": "astro",
  ".bat": "bat",
  ".bib": "bibtex",
  ".bibtex": "bibtex",
  ".c": "c",
  ".c++": "cpp",
  ".cc": "cpp",
  ".cjs": "javascript",
  ".clj": "clojure",
  ".cljs": "clojure",
  ".cljc": "clojure",
  ".coffee": "coffeescript",
  ".cpp": "cpp",
  ".cs": "csharp",
  ".cshtml": "razor",
  ".css": "css",
  ".css.erb": "erb",
  ".cts": "typescript",
  ".ctsx": "typescriptreact",
  ".cxx": "cpp",
  ".d": "d",
  ".dart": "dart",
  ".diff": "diff",
  ".dockerfile": "dockerfile",
  ".edn": "clojure",
  ".erb": "erb",
  ".erl": "erlang",
  ".ets": "typescript",
  ".ex": "elixir",
  ".exs": "elixir",
  ".fs": "fsharp",
  ".fsi": "fsharp",
  ".fsscript": "fsharp",
  ".fsx": "fsharp",
  ".gitcommit": "git-commit",
  ".gitrebase": "git-rebase",
  ".gleam": "gleam",
  ".go": "go",
  ".gemspec": "ruby",
  ".groovy": "groovy",
  ".hbs": "handlebars",
  ".handlebars": "handlebars",
  ".hcl": "hcl",
  ".hrl": "erlang",
  ".hs": "haskell",
  ".htm": "html",
  ".html": "html",
  ".html.erb": "erb",
  ".ini": "ini",
  ".jade": "jade",
  ".java": "java",
  ".jl": "julia",
  ".js": "javascript",
  ".js.erb": "erb",
  ".json": "json",
  ".json.erb": "erb",
  ".jsx": "javascriptreact",
  ".ksh": "shellscript",
  ".kt": "kotlin",
  ".kts": "kotlin",
  ".latex": "latex",
  ".less": "less",
  ".lhs": "haskell",
  ".lua": "lua",
  ".m": "objective-c",
  ".makefile": "makefile",
  ".markdown": "markdown",
  ".md": "markdown",
  ".mjs": "javascript",
  ".ml": "ocaml",
  ".mli": "ocaml",
  ".mm": "objective-cpp",
  ".mts": "typescript",
  ".mtsx": "typescriptreact",
  ".nix": "nix",
  ".pas": "pascal",
  ".pascal": "pascal",
  ".patch": "diff",
  ".php": "php",
  ".pl": "perl",
  ".pm": "perl",
  ".pm6": "perl6",
  ".ps1": "powershell",
  ".psm1": "powershell",
  ".pug": "jade",
  ".py": "python",
  ".r": "r",
  ".rake": "ruby",
  ".razor": "razor",
  ".rb": "ruby",
  ".rs": "rust",
  ".ru": "ruby",
  ".sass": "sass",
  ".scala": "scala",
  ".scss": "scss",
  ".shader": "shaderlab",
  ".sh": "shellscript",
  ".sql": "sql",
  ".svelte": "svelte",
  ".swift": "swift",
  ".tex": "latex",
  ".tf": "terraform",
  ".tfvars": "terraform-vars",
  ".ts": "typescript",
  ".tsx": "typescriptreact",
  ".typ": "typst",
  ".typc": "typst",
  ".vue": "vue",
  ".xml": "xml",
  ".xsl": "xsl",
  ".yaml": "yaml",
  ".yml": "yaml",
  ".zig": "zig",
  ".zon": "zig",
  ".zsh": "shellscript",
  makefile: "makefile",
} as const;

const TYPESCRIPT_FILETYPES = new Set(["javascript", "javascriptreact", "typescriptreact"]);

export function getDiffFiletype(input?: string): string | undefined {
  if (!input) {
    return "none";
  }

  const normalizedPath = input.toLowerCase();
  const extension = path.extname(normalizedPath);
  const language =
    LANGUAGE_EXTENSIONS[extension] ?? LANGUAGE_EXTENSIONS[path.basename(normalizedPath)];

  if (language == null) {
    return undefined;
  }

  if (TYPESCRIPT_FILETYPES.has(language)) {
    return "typescript";
  }

  return language;
}
